apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: moat-mcp-server
  labels:
    app: moat
    component: mcp-server
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "5"
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 30
      containers:
        - image: us-docker.pkg.dev/irsb-protocol/moat/mcp-server:latest
          ports:
            - containerPort: 8004
          env:
            - name: MOAT_ENV
              value: production
            - name: PORT
              value: "8004"
            - name: MOAT_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: moat-jwt-secret
                  key: latest
            - name: MOAT_AUTH_DISABLED
              value: "false"
            - name: CONTROL_PLANE_URL
              value: https://moat-control-plane-xxxxxxxxxx.run.app
            - name: GATEWAY_URL
              value: https://moat-gateway-xxxxxxxxxx.run.app
            - name: TRUST_PLANE_URL
              value: https://moat-trust-plane-xxxxxxxxxx.run.app
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
          startupProbe:
            httpGet:
              path: /healthz
              port: 8004
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8004
            periodSeconds: 15
