name: Bug Report
description: Report a bug in Moat
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Clear description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to trigger the bug.
      placeholder: |
        1. Call POST /execute/...
        2. With params: ...
        3. See error: ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: "0.1.0"
  - type: dropdown
    id: service
    attributes:
      label: Affected service
      options:
        - Control Plane
        - Gateway
        - Trust Plane
        - MCP Server
        - Core Package
        - Other
